# $Id$
# $(c)$

source 'http://rubygems.org'

gem 'active_record_query_trace', '1.4'
gem 'activerecord-import', '0.7.0'
gem 'activerecord-session_store', '0.1.1'
gem 'airbrake', '4.1.0'
gem 'bootstrap-sass', '3.3.4.1'
gem 'cancancan', '1.10.1'
gem 'devise', '3.4.1'
gem 'exception_notification', '4.1.0'
gem 'fastercsv', '1.5.5'
gem 'haml', '4.0.6'
gem 'httpclient', '2.6.0.1'
gem 'httparty', '0.13.3'
gem 'jquery-rails', '4.0.3'
gem 'jquery-ui-rails', '5.0.3'
gem 'jquery-migrate-rails', '1.2.1' # TODO: can jquery-migrate-rails be removed?
gem 'lograge', '0.3.1'
gem 'mysql2', '0.3.18'
gem 'passenger', '5.0.6'
gem 'rails', '4.2.1'
gem 'rails-html-sanitizer', '1.0.2'
gem 'rails-i18n', '4.0.4'
gem 'rake', '10.4.2'
gem 'rbtrace'
gem 'rubygems-update'
gem 'sass-rails', '5.0.3'
gem 'simplecov', '0.9.2', group: :test
gem 'smart_listing', '1.1.2'
gem 'sprockets-rails', '2.2.4'
gem 'test-unit'
gem 'therubyracer', '0.12.2',  platforms: :ruby
gem 'tracer_bullets', '0.0.5'
gem 'turbolinks', '2.5.3'
gem 'uglifier', '2.7.1'
gem 'yui-compressor', '0.12.0'

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman'
  gem 'erb2haml'
  gem 'flay'
  gem 'flog'
  gem 'html2haml'
  gem 'meta_request', '0.3.4'
  gem 'quiet_assets'
  gem 'rails_best_practices'
  gem 'rails_layout'
  gem 'reek'
  gem 'rubocop'
end
